name       : birdtray
version    : 1.8.0
release    : 2
source     :
    - https://github.com/gyunaev/birdtray/archive/1.8.0.tar.gz : 590e3d7ffc20a9617811bbadefcc216090b326fd66b7b7fd47b1387d40d70577
license    : GPL-3.0-or-later
component  : desktop
summary    : Mail system tray notification icon for Thunderbird
description: |
    Birdtray is a free system tray notification for new mail for Thunderbird.
homepage   : https://github.com/gyunaev/birdtray
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
rundeps    :
    - thunderbird
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
