name       : birdtray
version    : 1.7.0
release    : 1
source     :
    - https://github.com/gyunaev/birdtray/archive/RELEASE_1.7.0.tar.gz : db7d09af30b6323cd8b7da18fdb8dfd19696ab02c9dbe4b18cfd070afedd044a
license    : GPL-3.0-or-later
component  : desktop
summary    : Mail system tray notification icon for Thunderbird
description: |
    Birdtray is a free system tray notification for new mail for Thunderbird.
homepage   : https://github.com/gyunaev/birdtray
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sqlite3)
rundeps    :
    - thunderbird
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
